# Generated by Django 6.0.2 on 2026-04-26 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва команди')),
                ('city_school', models.CharField(blank=True, max_length=255, verbose_name='Місто / школа')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Telegram / Discord')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата реєстрації')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ учасника')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('is_captain', models.BooleanField(default=False, verbose_name='Капітан')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учасник команди',
                'verbose_name_plural': 'Учасники команд',
                'unique_together': {('team', 'email')},
            },
        ),
    ]
