# Generated by Django 5.1.7 on 2026-04-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
    ]
