# Generated by Django 5.1.7 on 2026-05-19 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tech_requirements', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('submission_closed', 'Submission closed'), ('evaluated', 'Evaluated')], default='active', max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['tournament_id', 'order'],
                'unique_together': {('tournament', 'order')},
            },
        ),
        migrations.CreateModel(
            name='MustHaveCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('order', models.PositiveIntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='must_have_criteria', to='tournaments.round')),
            ],
            options={
                'ordering': ['round_id', 'order'],
                'unique_together': {('round', 'order')},
            },
        ),
    ]
